import type { Metadata } from "next";
import { font } from "@/lib/designSystem";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: font.family.ui, fontVariantNumeric: "lining-nums" }}>{children}</body>
    </html>
  );
}
